[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.10.1"
hex-literal = "0.2.1"
base64 = "0.13.0"
rand = "0.8.4"
url = "2.2.2"
actix-web = { version = "3.3.3", features = ["openssl"] }
actix-session = "0.4.1"
futures = "0.3.19"
tokio = { version = "1", features = ["full"] }
bson = "2.1.0"
redis = "0.21.5"
futures-util = "0.3.17"
mongodb = { version = "2.1.0", default-features = false, features = ["async-std-runtime"] }
serde = { version = "1.0", features = ["derive"] }
actix-redis = "0.9.2"
actix-rt = "1.0"
querystring = "1.1.0"
serde_json = "1.0.78"
openssl = "0.10.38"
awc = "2.0.3"
time = { version = "0.2", features = ["serde"] }
json_value_merge = "1.1.2"
actix-cors = "0.5.4"
shuuro = "0.5.87"
actix-web-actors = "3"
actix = "0.10.0"
uuid = { version = "0.8", features = ["v4", "serde"] }
itertools = "0.10"
bitintr = "0.3"
thiserror = "1.0"
